apiVersion: v1
kind: Service
metadata:
  name: spring-boot-sample
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: spring-boot-sample
  sessionAffinity: None
  type: ClusterIP
